#!/usr/bin/env python

import argparse
import os
import SimpleHTTPServer
import SocketServer


def main():
    parser = argparse.ArgumentParser(description="Run a local Game Play server.")
    parser.add_argument("--port", default=8888, type=int, help="Listening port.")
    options = parser.parse_args()

    httpd = SocketServer.TCPServer(("", options.port), SimpleHTTPServer.SimpleHTTPRequestHandler)
    print "Serving on http://127.0.0.1:%d..." % options.port
    httpd.serve_forever()


if __name__ == "__main__":
    main()
